### ISSUE TITLE
Create an endpoint to create a new game 

### ISSUE THREAD

**Issue by Alao-Abiodun** [zurichat/zc_plugin_chessboard#226]
and the endpoint does the following below:
- [x] takes in game options
- [x] returns a unique game_id using uuid.v4()

Here is a test link for the endpoint
Visit 
https://chess.zuri.chat/test
Now when you click the createGame button, it will display the game Id for that game session.

**Comment by markessien** [comment]
No testing link

**Comment by Alao-Abiodun** [comment]
Here is a test link for endpoint
https://chess.zuri.chat/api/createGame Prior to this you will be redirected to https://chess.zuri.chat

**Comment by markessien** [comment]
Not testable. Clicking the button does nothing

**Comment by Alao-Abiodun** [comment]
@markessien yes we are only getting the game Id and options, when the FE design the UI to show when you click the start game

**Comment by Alao-Abiodun** [comment]
> Not testable. Clicking the button does nothing

**Comment by markessien** [comment]
This ticket is really not a good ticket and I don't think it will ever be accepted. It looks like you are doing your own socket implementation, but that is not how this project works. You need to use our central data transfer method.
