### ISSUE TITLE
Create a socket event listener for "Player Move Made" and broadcast it to the room with "game_id"

### ISSUE THREAD

**Issue by Alao-Abiodun** [zurichat/zc_plugin_chessboard#232]

**Comment by NdubuisiJr** [comment]
This issue has been implemented 

PR: https://github.com/zurichat/zc_plugin_chessboard/pull/286

Test Link: https://chess.zuri.chat/test

**Comment by markessien** [comment]
We have a central socket method. Plugins do not create their own rooms

**Comment by NdubuisiJr** [comment]
Issue solved by this PR: https://github.com/zurichat/zc_plugin_chessboard/pull/408

This integrates the centrifugo web socket.
Live link: https://chess.zuri.chat/test
