### ISSUE TITLE
Setup the backend project files and Setup express server to serve the react frontend

### ISSUE THREAD

**Issue by eni4sure** [zurichat/zc_plugin_chessboard#252]
To test
Visit https://chess.zuri.chat/api/ping to serve an API from the backend

Any random URL not defined by the backend will redirect to the react app
e.g https://chess.zuri.chat/jhbfeni 

CC: @Generalsoi

**Comment by eni4sure** [comment]
CC: @Generalsoi

**Comment by markessien** [comment]
Looks good!
