### ISSUE TITLE
Create an endpoint to update a game result in each game created.

### ISSUE THREAD

**Issue by Alao-Abiodun** [zurichat/zc_plugin_chessboard#431]

**Comment by kenny0619** [comment]
kenny0619:update-game-result

**Comment by kenny0619** [comment]
create result data by taking winner_id and game_id
query game with object_id
add result_id to update the game data
save to the db
send a PATCH request to https://chess.zuri.chat/api/dbUpdateResult 
body: {
    "winner_id": "613468882d91654fa0486339 ",
    "game_id": "61346e172d91654fa048633c"
}

**Comment by kenny0619** [comment]
@eni4sure
